export enum AbortCondition {
    RATE_LIMIT_DETECTED = "RATE_LIMIT_DETECTED",
    CHALLENGE_DETECTED = "CHALLENGE_DETECTED",
    LOGIN_REQUIRED = "LOGIN_REQUIRED",
    SESSION_INVALID = "SESSION_INVALID",
    ACCOUNT_PAUSED = "ACCOUNT_PAUSED",
    MANNUAL_ABORT = "MANNUAL_ABORT"
}