
import { Account, AccountEvent } from '../types';

export const MOCK_ACCOUNTS: Account[] = [
  {
    accountId: "acc_001",
    username: "growth_engine_01",
    fullName: "Growth Engine Official",
    state: "ACTIVE",
    trustScore: 94,
    riskLevel: "LOW",
    lastEventAt: "2024-05-20T10:30:00Z",
    automationStatus: "Allowed",
    tags: ["Region:US", "Priority:High", "Tier:Gold"],
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=growth",
    bio: "Optimizing audience reach through intelligent engagement patterns. 🚀 ✨",
    postsCount: 342,
    followersCount: 12400,
    followingCount: 890,
    website: "growth-engine.io"
  },
  {
    accountId: "acc_002",
    username: "nexus_social_prime",
    fullName: "Nexus Social",
    state: "PAUSED",
    trustScore: 42,
    riskLevel: "MEDIUM",
    lastEventAt: "2024-05-20T11:45:00Z",
    automationStatus: "Limited",
    tags: ["Beta-Fleet", "Legacy-Proxy", "Retail"],
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=nexus",
    bio: "The central hub for social connectivity. Currently undergoing maintenance.",
    postsCount: 1205,
    followersCount: 85200,
    followingCount: 120,
    website: "nexus.prime"
  },
  {
    accountId: "acc_003",
    username: "shadow_bot_alpha",
    fullName: "Alpha Protocol",
    state: "FROZEN",
    trustScore: 12,
    riskLevel: "HIGH",
    lastEventAt: "2024-05-20T09:15:00Z",
    automationStatus: "Blocked",
    tags: ["Quarantine", "Investigation", "Shadow-Ops"],
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=alpha",
    bio: "[ENCRYPTED] High volume data aggregation and stealth networking.",
    postsCount: 50,
    followersCount: 1200,
    followingCount: 5400,
    website: "hidden.onion"
  },
  {
    accountId: "acc_004",
    username: "eco_warrior_insta",
    fullName: "Eco Warrior",
    state: "ACTIVE",
    trustScore: 78,
    riskLevel: "LOW",
    lastEventAt: "2024-05-19T22:00:00Z",
    automationStatus: "Allowed",
    tags: ["Region:EU", "Niche:Eco", "Verified"],
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=eco",
    bio: "Saving the planet, one post at a time. 🌱 Verified organic growth fleet.",
    postsCount: 890,
    followersCount: 45000,
    followingCount: 320,
    website: "save-earth.org"
  },
  {
    accountId: "acc_005",
    username: "tech_guru_feeds",
    fullName: "Guru Tech",
    state: "ACTIVE",
    trustScore: 55,
    riskLevel: "MEDIUM",
    lastEventAt: "2024-05-20T12:00:00Z",
    automationStatus: "Limited",
    tags: ["Warm-up", "Tech"],
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=tech",
    bio: "Breaking tech news and deep dives into AI. 🤖",
    postsCount: 215,
    followersCount: 12500,
    followingCount: 450,
    website: "techguru.com"
  },
  {
    accountId: "acc_006",
    username: "crypto_whale_tracker",
    fullName: "Whale Tracker",
    state: "ACTIVE",
    trustScore: 89,
    riskLevel: "LOW",
    lastEventAt: "2024-05-20T14:20:00Z",
    automationStatus: "Allowed",
    tags: ["Finance", "High-Volume"],
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=crypto",
    bio: "Monitoring on-chain movement 24/7. HODL. 🐳 💎",
    postsCount: 5602,
    followersCount: 128000,
    followingCount: 10,
    website: "whale.watch"
  },
  {
    accountId: "acc_007",
    username: "pixel_perfect_ads",
    fullName: "Pixel Perfect",
    state: "PAUSED",
    trustScore: 28,
    riskLevel: "HIGH",
    lastEventAt: "2024-05-20T15:10:00Z",
    automationStatus: "Blocked",
    tags: ["Ad-Manager", "Review-Required"],
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=pixel",
    bio: "Digital advertising agency focusing on high-conversion visual storytelling.",
    postsCount: 45,
    followersCount: 2300,
    followingCount: 2300,
    website: "pixel.ads"
  },
  {
    accountId: "acc_008",
    username: "travel_junkie_bot",
    fullName: "Travel Junkie",
    state: "ACTIVE",
    trustScore: 64,
    riskLevel: "MEDIUM",
    lastEventAt: "2024-05-20T08:00:00Z",
    automationStatus: "Limited",
    tags: ["Lifestyle", "EU-Proxy"],
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=travel",
    bio: "Exploring the world's most beautiful destinations. ✈️ 🌍",
    postsCount: 1240,
    followersCount: 67000,
    followingCount: 1200,
    website: "traveljunkie.com"
  },
  {
    accountId: "acc_009",
    username: "fitness_first_auto",
    fullName: "Fitness First",
    state: "ACTIVE",
    trustScore: 91,
    riskLevel: "LOW",
    lastEventAt: "2024-05-20T13:45:00Z",
    automationStatus: "Allowed",
    tags: ["Health", "Static-IP"],
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=fitness",
    bio: "Transforming lives through daily motivation and workout routines. 💪",
    postsCount: 670,
    followersCount: 29000,
    followingCount: 400,
    website: "fitnessfirst.io"
  },
  {
    accountId: "acc_010",
    username: "gaming_news_relay",
    fullName: "Gaming Relay",
    state: "FROZEN",
    trustScore: 5,
    riskLevel: "HIGH",
    lastEventAt: "2024-05-20T16:00:00Z",
    automationStatus: "Blocked",
    tags: ["Entertainment", "Banned-Attempt"],
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=gaming",
    bio: "The latest updates from the gaming world. Currently offline due to security breach.",
    postsCount: 12,
    followersCount: 500,
    followingCount: 0,
    website: "gaming.relay"
  }
];

export const MOCK_EVENTS: AccountEvent[] = [
  {
    id: "evt_1",
    accountId: "acc_003",
    type: "RATE_LIMIT_WARNING",
    severity: "CRITICAL",
    description: "Maximum API call threshold exceeded. Account throttled by provider.",
    timestamp: "2024-05-20T09:10:00Z"
  },
  {
    id: "evt_2",
    accountId: "acc_002",
    type: "LOGIN_FAILED",
    severity: "WARNING",
    description: "Suspicious login attempt detected from unknown IP 192.168.1.102.",
    timestamp: "2024-05-20T11:40:00Z"
  },
  {
    id: "evt_3",
    accountId: "acc_001",
    type: "MANUAL_OVERRIDE",
    severity: "INFO",
    description: "Operator reset trust score to 94.",
    timestamp: "2024-05-20T10:30:00Z"
  },
  {
    id: "evt_4",
    accountId: "acc_007",
    type: "AUTOMATION_BLOCKED",
    severity: "CRITICAL",
    description: "Instagram challenged session integrity. Checkpoint required.",
    timestamp: "2024-05-20T15:05:00Z"
  },
  {
    id: "evt_5",
    accountId: "acc_010",
    type: "STATE_CHANGE",
    severity: "CRITICAL",
    description: "System auto-freeze triggered: Trust score dropped below critical threshold (5%).",
    timestamp: "2024-05-20T16:00:00Z"
  },
  {
    id: "evt_6",
    accountId: "acc_005",
    type: "TRUST_RECOVERY",
    severity: "INFO",
    description: "Positive cooldown period completed. Trust score +5.",
    timestamp: "2024-05-20T12:00:00Z"
  },
  {
    id: "evt_7",
    accountId: "acc_008",
    type: "RATE_LIMIT_WARNING",
    severity: "WARNING",
    description: "Heavy interaction burst detected. Engagement speed throttled to 50%.",
    timestamp: "2024-05-20T07:45:00Z"
  }
];
